// fe_vue/src/views/Login.vue
<template>
    <div class="container">
        <h1>Login</h1>
        <form @submit.prevent="handleLogin">
            <div class="mb-3">
                <label for="username" class="form-label">Username</label>
                <input v-model="username" type="text" class="form-control" id="username" required />
            </div>
            <div class="mb-3">
                <label for="password" class="form-label">Password</label>
                <input v-model="password" type="password" class="form-control" id="password" required />
            </div>
            <button type="submit" class="btn btn-primary">Login</button>
        </form>
    </div>
</template>
  
<script>
import { useAuthStore } from '../store/auth';

export default {
    data() {
        return {
        username: '',
        password: '',
        };
    },
    methods: {
        async handleLogin() {
        const authStore = useAuthStore();
        try {
            await authStore.login(this.username, this.password);
            this.$router.push('/profile'); // Redirect to profile after login
        } catch (error) {
            alert('Login failed');
        }
        },
    },
};
</script>

// fe_react/src/pages/Login.jsx
import { useAtom } from 'jotai';
import { usernameAtom } from '../atoms/usernameAtom';
import { useNavigate } from 'react-router-dom';
import { useState } from 'react';
import axios from 'axios';

export default function Login() {
  const [, setUsername] = useAtom(usernameAtom); // Set username only in Jotai
  const navigate = useNavigate();
  const [username, setUsernameInput] = useState('');
  const [password, setPassword] = useState('');

  const handleLogin = async (e) => {
    e.preventDefault();
    try {
      const response = await axios.post('http://127.0.0.1:8000/api/login', { username, password });
      
      // Store token and isAuthenticated status in localStorage
      localStorage.setItem('token', response.data.token);
      localStorage.setItem('isAuthenticated', 'true');

      // Store username in Jotai for Profile display
      setUsername(username);

      navigate('/dashboard');
    } catch (error) {
      console.error('Login failed', error);
      alert('Invalid credentials');
    }
  };

  return (
    <div className="container">
      <h2>Login</h2>
      <form onSubmit={handleLogin}>
        <div className="mb-3">
          <label className="form-label">Username</label>
          <input type="text" className="form-control" value={username} onChange={(e) => setUsernameInput(e.target.value)} />
        </div>
        <div className="mb-3">
          <label className="form-label">Password</label>
          <input type="password" className="form-control" value={password} onChange={(e) => setPassword(e.target.value)} />
        </div>
        <button type="submit" className="btn btn-primary">Login</button>
      </form>
    </div>
  );
}
